[project]
name = "apktool-mcp-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.2.0",
    "logging>=0.4.9.6",
    "supabase>=2.16.0",
    "fastapi>=0.110",
    "uvicorn>=0.27",
]
